import React, { useEffect, useState, useContext, useRef } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { IoIosLogIn } from "react-icons/io";
import Navbar from '../Navbar'


export default function MainLayout({ children }) {
    // 導覽列
    return (
        <>
            <div className="my-container-fluid">
                <Head>
                    <title>Chic Boutique</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <header className="row">
                    <Navbar /> 
                </header>
                <main className="row">
                    {children}
                </main>
                <footer className='xs-close'>
                    <ul>
                        <li><IoIosLogIn className='icon' /></li>
                    </ul>
                </footer>

            </div>
        </>
    )
}
